# -*- coding: utf-8 -*-
"""FIX recrutamento_pro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3mwSuWrT-UNtcsna87FYhkFjJpcUIgR

# --- PARTE 1: CONFIGURAÇÃO INICIAL E IMPORTAÇÃO DE BIBLIOTECAS ---
"""

# --- PARTE 1: CONFIGURAÇÃO INICIAL E IMPORTAÇÃO DE BIBLIOTECAS ---

# --- PARTE 1: INSTALAÇÃO E CONFIGURAÇÃO INICIAL ---
# 1.1. Instalação de Bibliotecas
!pip install streamlit pyngrok scikit-learn pandas numpy plotly_express sqlalchemy --quiet

# 1.2. Importação de Bibliotecas Essenciais
import pandas as pd
import json
import os
from datetime import datetime
import joblib
import numpy as np
from sklearn.linear_model import LogisticRegression
from sqlalchemy import create_engine, Column, String, Integer, DateTime, Text
from sqlalchemy.orm import sessionmaker, declarative_base
import sqlite3

# 1.3. Configuração do Banco de Dados SQLite
Base = declarative_base()

class Candidatura(Base):
    __tablename__ = 'candidaturas'
    id = Column(Integer, primary_key=True, autoincrement=True)
    vaga = Column(String(255))
    nome = Column(String(255))
    email = Column(String(255))
    linkedin = Column(String(255))
    experiencia = Column(String(50))
    escolaridade = Column(String(50))
    nivel_ingles = Column(String(50))
    nivel_espanhol = Column(String(50))
    habilidades = Column(Text)  # NOVO CAMPO ADICIONADO
    cv = Column(String(255))
    data_hora = Column(DateTime)

# Criar banco de dados e tabela
engine = create_engine('sqlite:///candidatos.db')
Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)

# 1.4. Carregar ou criar dados de vagas em formato unificado
SOURCE_FILE = "vagas.json"
TARGET_FILE = "jobs_sample.json"

if not os.path.exists(SOURCE_FILE):
    print(f"❌ Arquivo '{SOURCE_FILE}' não encontrado. Criando dados dummy alternativos em '{TARGET_FILE}'...")

    dummy_jobs_data = {
        "vaga_999": {
            "titulo": "Dummy Backup",
            "cliente": "Sistema",
            "perfil_vaga": {
                "cidade": "São Paulo",
                "estado": "SP",
                "pais": "Brasil",
                "nivel_profissional": "Sênior",
                "nivel_ingles": "Avançado",
                "nivel_espanhol": "Intermediário",
                "competencias": ["Python", "SQL", "Backup"],
                "atividades": ["Manutenção do sistema", "Backup de dados"]
            }
        }
    }
    with open(TARGET_FILE, "w", encoding="utf-8") as f:
        json.dump(dummy_jobs_data, f, indent=4, ensure_ascii=False)
    print(f"✅ '{TARGET_FILE}' criado com dados dummy de backup")
else:
    try:
        with open(SOURCE_FILE, "r", encoding="utf-8") as f:
            vagas_data = json.load(f)

        jobs_data = {}
        for vid, det in vagas_data.items():
            perfil = det.get("perfil_vaga", {})
            # extrair listas de competências e atividades
            comps = perfil.get("competencia_tecnicas_e_comportamentais", "")
            atvs = perfil.get("principais_atividades", "")
            lista_comps = [c.strip() for c in comps.split("\n") if c.strip()] if isinstance(comps, str) else comps
            lista_atvs  = [a.strip() for a in atvs.split("\n") if a.strip()] if isinstance(atvs, str) else atvs

            jobs_data[f"vaga_{vid}"] = {
                "titulo": det.get("informacoes_basicas", {}).get("titulo_vaga", "Título não especificado"),
                "cliente": det.get("informacoes_basicas", {}).get("cliente", "Cliente não especificado"),
                "perfil_vaga": {
                    "cidade": perfil.get("cidade", ""),
                    "estado": perfil.get("estado", ""),
                    "pais": perfil.get("pais", ""),
                    "nivel_profissional": perfil.get("nivel_profissional", ""),
                    "nivel_ingles": perfil.get("nivel_ingles", ""),
                    "nivel_espanhol": perfil.get("nivel_espanhol", ""),
                    "competencias": lista_comps,
                    "atividades": lista_atvs
                }
            }

        with open(TARGET_FILE, "w", encoding="utf-8") as f:
            json.dump(jobs_data, f, indent=4, ensure_ascii=False)
        print(f"✅ '{TARGET_FILE}' criado com {len(jobs_data)} vagas reais")
    except Exception as e:
        print(f"❌ Erro ao processar '{SOURCE_FILE}': {e}")
        print("Criando dados dummy de fallback...")
        fallback = {
            "vaga_999": {
                "titulo": "Dummy Fallback",
                "cliente": "Sistema",
                "perfil_vaga": {
                    "cidade": "São Paulo",
                    "estado": "SP",
                    "pais": "Brasil",
                    "nivel_profissional": "Pleno",
                    "nivel_ingles": "Intermediário",
                    "nivel_espanhol": "Básico",
                    "competencias": ["Fallback", "Recuperação"],
                    "atividades": ["Recuperar sistema", "Manter operação"]
                }
            }
        }
        with open(TARGET_FILE, "w", encoding="utf-8") as f:
            json.dump(fallback, f, indent=4, ensure_ascii=False)
        print(f"✅ '{TARGET_FILE}' criado com dados dummy de fallback")

# 1.5. Criação de um modelo dummy para análise preditiva
dummy_model_data = {
    "experiencia": np.random.randint(0, 5, 100),
    "escolaridade": np.random.randint(0, 7, 100),
    "nivel_ingles": np.random.randint(0, 5, 100),
    "nivel_espanhol": np.random.randint(0, 5, 100),
    "target": np.random.randint(0, 2, 100)
}
df_dummy = pd.DataFrame(dummy_model_data)
X_dummy = df_dummy[["experiencia", "escolaridade", "nivel_ingles", "nivel_espanhol"]]
y_dummy = df_dummy["target"]
modelo = LogisticRegression()
modelo.fit(X_dummy, y_dummy)
joblib.dump(modelo, "modelo_vagas.pkl")
print("✅ 'modelo_vagas.pkl' criado")

"""# --- PARTE 2: FUNÇÕES AUXILIARES DE DADOS E PRÉ-PROCESSAMENTO ---"""

# --- PARTE 2: APLICATIVO STREAMLIT ---
import streamlit as st
import pandas as pd
import json
import os
from datetime import datetime
import joblib
import plotly.express as px
import sqlite3

# Configuração da página
st.set_page_config(
    page_title="Plataforma de Vagas - Datathon",
    layout="wide",
    page_icon="💼"
)

# Mapeamentos globais para formulários e pré-processamento
experiencia_map = {
    "Estagiário": 0,
    "Júnior": 1,
    "Pleno": 2,
    "Sênior": 3,
    "Especialista": 4
}

escolaridade_map = {
    "Ensino Médio": 0,
    "Técnico": 1,
    "Superior Incompleto": 2,
    "Superior Completo": 3,
    "Pós-graduação": 4,
    "Mestrado": 5,
    "Doutorado": 6
}

idioma_map = {
    "Nenhum": 0,
    "Básico": 1,
    "Intermediário": 2,
    "Avançado": 3,
    "Fluente": 4
}

# Funções de banco de dados
def init_db():
    """Inicializa o banco de dados SQLite"""
    conn = sqlite3.connect('candidatos.db')
    c = conn.cursor()
    c.execute('''
        CREATE TABLE IF NOT EXISTS candidaturas (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            vaga TEXT,
            nome TEXT,
            email TEXT,
            linkedin TEXT,
            experiencia TEXT,
            escolaridade TEXT,
            nivel_ingles TEXT,
            nivel_espanhol TEXT,
            habilidades TEXT,
            cv TEXT,
            data_hora DATETIME
        )
    ''')
    conn.commit()
    conn.close()

def salvar_candidato_db(dados):
    """Salva candidatura no banco de dados"""
    try:
        conn = sqlite3.connect('candidatos.db')
        c = conn.cursor()
        dados["data_hora"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        c.execute('''
            INSERT INTO candidaturas
            (vaga, nome, email, linkedin, experiencia, escolaridade, nivel_ingles, nivel_espanhol, habilidades, cv, data_hora)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            dados['vaga'], dados['nome'], dados['email'], dados['linkedin'],
            dados['experiencia'], dados['escolaridade'], dados['nivel_ingles'],
            dados['nivel_espanhol'], dados['habilidades'], dados['cv'], dados['data_hora']
        ))
        conn.commit()
        conn.close()
        return True
    except Exception as e:
        st.error(f"Erro ao salvar candidatura: {str(e)}")
        return False

def carregar_candidaturas():
    """Carrega todas as candidaturas do banco de dados"""
    try:
        conn = sqlite3.connect('candidatos.db')
        df = pd.read_sql_query("SELECT * FROM candidaturas", conn)
        conn.close()
        return df
    except Exception as e:
        st.error(f"Erro ao carregar candidaturas: {str(e)}")
        return pd.DataFrame()

# Função para carregar vagas
def carregar_vagas():
    try:
        with open("jobs_sample.json", "r", encoding="utf-8") as f:
            data = json.load(f)

        vagas = []
        for vid, det in data.items():
            perfil = det["perfil_vaga"]
            vagas.append({
                "title": det["titulo"],
                "company": det["cliente"],
                "location": f"{perfil['cidade']}, {perfil['estado']} - {perfil['pais']}",
                "contract_type": "Não informado",
                "salary": "Não informado",
                "description": "; ".join(perfil.get("atividades", [])),
                "requirements": "; ".join(perfil.get("competencias", []))
            })
        return vagas
    except Exception as e:
        st.error(f"Erro ao carregar vagas: {e}")
        return []

# Função de pré-processamento ATUALIZADA
def preprocess(df):
    df2 = df.copy()

    # Converter para string para garantir compatibilidade
    for col in ["experiencia", "escolaridade", "nivel_ingles", "nivel_espanhol"]:
        if col in df2.columns:
            df2[col] = df2[col].astype(str)

    # Mapeamento seguro
    for col, mapping in [
        ("experiencia", experiencia_map),
        ("escolaridade", escolaridade_map),
        ("nivel_ingles", idioma_map),
        ("nivel_espanhol", idioma_map)
    ]:
        if col in df2.columns:
            # Mapear valores e tratar não encontrados
            df2[col] = df2[col].map(lambda x: mapping.get(x.strip(), 0))
        else:
            df2[col] = 0

    return df2[["experiencia", "escolaridade", "nivel_ingles", "nivel_espanhol"]].fillna(0).astype(int)

# Inicialização do banco de dados
init_db()

# Navegação
menu = st.sidebar.radio(
    "📂 Navegação",
    ["📌 Aplicar para Vagas", "🧠 Recrutamento Decision", "📊 Banco de Candidaturas"]
)

if menu == "📌 Aplicar para Vagas":
    st.title("📌 Plataforma de Vagas - Datathon")
    vagas = carregar_vagas()

    if vagas:
        escolha = st.selectbox(
            "Selecione a vaga",
            options=[v["title"] for v in vagas],
            index=0
        )

        vaga = next(v for v in vagas if v["title"] == escolha)

        st.subheader(vaga["title"])
        col1, col2 = st.columns(2)
        with col1:
            st.write(f"**Empresa:** {vaga['company']}")
            st.write(f"**Localização:** {vaga['location']}")
        with col2:
            st.write(f"**Tipo de Contrato:** {vaga['contract_type']}")
            st.write(f"**Salário:** {vaga['salary']}")

        st.write("---")
        st.write(f"**Descrição:** {vaga['description']}")
        st.write(f"**Requisitos:** {vaga['requirements']}")

        # Inicializar lista de habilidades na session_state
        if 'habilidades' not in st.session_state:
            st.session_state.habilidades = []

        # Inicializar estados para campos do formulário
        for field in ['nome', 'email', 'linkedin', 'experiencia', 'escolaridade', 'nivel_ingles', 'nivel_espanhol']:
            if field not in st.session_state:
                st.session_state[field] = ''

        with st.form("form_candidatura"):  # REMOVIDO: clear_on_submit=True
            st.subheader("Formulário de Candidatura")

            nome = st.text_input("Nome Completo*",
                                 placeholder="Seu nome completo",
                                 value=st.session_state.nome)

            email = st.text_input("Email*",
                                  placeholder="seu@email.com",
                                  value=st.session_state.email)

            linkedin = st.text_input("LinkedIn (opcional)",
                                     placeholder="https://linkedin.com/in/seu-perfil",
                                     value=st.session_state.linkedin)

            col1, col2 = st.columns(2)
            with col1:
                experiencia = st.selectbox(
                    "Nível de Experiência*",
                    list(experiencia_map.keys()),
                    index=list(experiencia_map.keys()).index(st.session_state.experiencia)
                    if st.session_state.experiencia in experiencia_map else 0
                )
                escolaridade = st.selectbox(
                    "Escolaridade*",
                    list(escolaridade_map.keys()),
                    index=list(escolaridade_map.keys()).index(st.session_state.escolaridade)
                    if st.session_state.escolaridade in escolaridade_map else 0
                )
            with col2:
                nivel_ingles = st.selectbox(
                    "Inglês*",
                    list(idioma_map.keys()),
                    index=list(idioma_map.keys()).index(st.session_state.nivel_ingles)
                    if st.session_state.nivel_ingles in idioma_map else 0
                )
                nivel_espanhol = st.selectbox(
                    "Espanhol*",
                    list(idioma_map.keys()),
                    index=list(idioma_map.keys()).index(st.session_state.nivel_espanhol)
                    if st.session_state.nivel_espanhol in idioma_map else 0
                )

            # Seção de Habilidades
            st.subheader("Habilidades Técnicas")
            nova_habilidade = st.text_input(
                "Digite uma habilidade e clique em Adicionar",
                placeholder="Ex: Python, SQL, etc.",
                key="nova_habilidade"
            )

            col_add, col_clear = st.columns(2)
            with col_add:
                adicionar_habilidade = st.form_submit_button("➕ Adicionar Habilidade")
            with col_clear:
                limpar_habilidades = st.form_submit_button("🧹 Limpar Todas")

            if adicionar_habilidade and nova_habilidade:
                st.session_state.habilidades.append(nova_habilidade.strip())
                st.rerun()

            if limpar_habilidades:
                st.session_state.habilidades = []
                st.rerun()

            if st.session_state.habilidades:
                st.write("**Habilidades adicionadas:**")
                for i, hab in enumerate(st.session_state.habilidades):
                    st.write(f"{i+1}. {hab}")

            enviar_cv = st.file_uploader(
                "Anexar CV (PDF ou DOCX)",
                type=["pdf", "docx"]
            )

            submitted = st.form_submit_button("Enviar Candidatura")

            if submitted:
                if not nome or not email:
                    st.error("⚠️ Campos obrigatórios não preenchidos (Nome e Email)")
                else:
                    dados = {
                        "vaga": escolha,
                        "nome": nome,
                        "email": email,
                        "linkedin": linkedin,
                        "experiencia": experiencia,
                        "escolaridade": escolaridade,
                        "nivel_ingles": nivel_ingles,
                        "nivel_espanhol": nivel_espanhol,
                        "habilidades": ", ".join(st.session_state.habilidades) if st.session_state.habilidades else "Nenhuma",
                        "cv": enviar_cv.name if enviar_cv else "Não enviado"
                    }

                    if salvar_candidato_db(dados):
                        st.success("✅ Candidatura enviada com sucesso!")
                        # Resetar apenas habilidades após envio
                        st.session_state.habilidades = []

                        # Manter outros campos para correção se necessário
                        st.session_state.nome = nome
                        st.session_state.email = email
                        st.session_state.linkedin = linkedin
                        st.session_state.experiencia = experiencia
                        st.session_state.escolaridade = escolaridade
                        st.session_state.nivel_ingles = nivel_ingles
                        st.session_state.nivel_espanhol = nivel_espanhol
                    else:
                        st.error("❌ Falha ao salvar candidatura")

    else:
        st.warning("Nenhuma vaga disponível no momento.")

elif menu == "🧠 Recrutamento Decision":
    st.title("🧠 Recrutamento Decision - Análise Preditiva")

    uploaded_file = st.file_uploader(
        "Carregue o arquivo CSV de candidatos",
        type=["csv"],
        help="O arquivo deve conter colunas para experiência, escolaridade e níveis de idioma"
    )

    if uploaded_file:
        df = pd.read_csv(uploaded_file)
        st.success("Arquivo carregado com sucesso!")

        with st.expander("Visualizar dados brutos"):
            st.dataframe(df.head())

        # Verificação de campos obrigatórios
        campos_necessarios = ["experiencia", "escolaridade", "nivel_ingles", "nivel_espanhol"]
        campos_faltantes = [campo for campo in campos_necessarios if campo not in df.columns]

        if campos_faltantes:
            st.warning(f"⚠️ Campos faltantes: {', '.join(campos_faltantes)}")
        else:
            st.subheader("Dados Pré-processados")
            X = preprocess(df)
            st.dataframe(X.head())

            if st.button("Executar Análise Preditiva"):
                try:
                    modelo = joblib.load("modelo_vagas.pkl")
                    df["score_sucesso"] = modelo.predict_proba(X)[:, 1]

                    st.subheader("🏆 Ranking de Candidatos")
                    st.dataframe(
                        df.sort_values("score_sucesso", ascending=False)
                        .style.background_gradient(subset=["score_sucesso"], cmap="YlGnBu")
                    )

                    st.subheader("📊 Distribuição de Scores")
                    fig = px.histogram(
                        df,
                        x="score_sucesso",
                        nbins=10,
                        title="Distribuição de Probabilidades de Sucesso"
                    )
                    st.plotly_chart(fig)

                    st.download_button(
                        "📥 Exportar Resultados",
                        data=df.to_csv(index=False).encode("utf-8"),
                        file_name="resultados_analise.csv",
                        mime="text/csv"
                    )

                except Exception as e:
                    st.error(f"Erro na análise: {str(e)}")

elif menu == "📊 Banco de Candidaturas":
    st.title("📊 Banco de Candidaturas")

    df_candidaturas = carregar_candidaturas()

    if not df_candidaturas.empty:
        st.dataframe(
            df_candidaturas.sort_values("data_hora", ascending=False)
        )

        col1, col2 = st.columns(2)
        with col1:
            st.metric(
                "Total de Candidaturas",
                len(df_candidaturas)
            )
        with col2:
            st.metric(
                "Vagas Únicas",
                df_candidaturas["vaga"].nunique()
            )

        st.download_button(
            "📥 Exportar Dados Completos",
            data=df_candidaturas.to_csv(index=False).encode("utf-8"),
            file_name="candidaturas_completas.csv",
            mime="text/csv"
        )
    else:
        st.info("Nenhuma candidatura registrada no banco de dados.")

"""# --- PARTE 3: CONFIGURAÇÃO DO NGROK ---"""

# --- PARTE 3: CONFIGURAÇÃO DO NGROK ---
import subprocess
import time
from pyngrok import ngrok
from IPython.display import clear_output
import os

# Token Ngrok - INSIRA SEU TOKEN AQUI!
NGROK_AUTH_TOKEN = "2wQHkXBUOtRPz53cch40jRcY9Z9_6M18JDPPBPT9XqCfsKHkP"

if not NGROK_AUTH_TOKEN:
    print("ERRO: Insira seu token Ngrok na variável NGROK_AUTH_TOKEN")
else:
    try:
        # Configurar autenticação
        ngrok.set_auth_token(NGROK_AUTH_TOKEN)

        # Salvar o aplicativo Streamlit em um arquivo
        STREAMLIT_SCRIPT = "streamlit_app.py"
        with open(STREAMLIT_SCRIPT, "w", encoding="utf-8") as f:
            f.write("""
# --- STREAMLIT APP SCRIPT ---
import streamlit as st
import pandas as pd
import json
import os
from datetime import datetime
import joblib
import plotly.express as px
import sqlite3

# Configuração da página
st.set_page_config(page_title="Plataforma de Vagas - Datathon", layout="wide")

# Mapeamentos globais
experiencia_map = {"Estagiário": 0, "Júnior": 1, "Pleno": 2, "Sênior": 3, "Especialista": 4}
escolaridade_map = {
    "Ensino Médio": 0, "Técnico": 1, "Superior Incompleto": 2,
    "Superior Completo": 3, "Pós-graduação": 4, "Mestrado": 5, "Doutorado": 6
}
idioma_map = {"Nenhum": 0, "Básico": 1, "Intermediário": 2, "Avançado": 3, "Fluente": 4}

# Função para salvar candidatura
def salvar_candidato_db(dados):
    try:
        conn = sqlite3.connect('candidatos.db')
        c = conn.cursor()
        dados["data_hora"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        c.execute('''
            INSERT INTO candidaturas
            (vaga, nome, email, linkedin, experiencia, escolaridade, nivel_ingles, nivel_espanhol, habilidades, cv, data_hora)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (dados['vaga'], dados['nome'], dados['email'], dados['linkedin'], dados['experiencia'],
              dados['escolaridade'], dados['nivel_ingles'], dados['nivel_espanhol'],
              dados['habilidades'], dados['cv'], dados['data_hora']))
        conn.commit()
        conn.close()
        return True
    except Exception as e:
        st.error(f"Erro ao salvar candidatura: {str(e)}")
        return False

# Função para carregar vagas
def carregar_vagas():
    try:
        with open("jobs_sample.json", "r", encoding="utf-8") as f:
            data = json.load(f)
        vagas = []
        for vid, det in data.items():
            perfil = det["perfil_vaga"]
            vagas.append({
                "title": det["titulo"],
                "company": det["cliente"],
                "location": f"{perfil['cidade']}, {perfil['estado']} - {perfil['pais']}",
                "contract_type": "Não informado",
                "salary": "Não informado",
                "description": "; ".join(perfil.get("atividades", [])),
                "requirements": "; ".join(perfil.get("competencias", []))
            })
        return vagas
    except Exception as e:
        st.error(f"Erro ao carregar vagas: {e}")
        return []

# Função de pré-processamento ATUALIZADA
def preprocess(df):
    df2 = df.copy()

    # Converter para string para garantir compatibilidade
    for col in ["experiencia", "escolaridade", "nivel_ingles", "nivel_espanhol"]:
        if col in df2.columns:
            df2[col] = df2[col].astype(str)

    # Mapeamento seguro
    for col, mapping in [
        ("experiencia", experiencia_map),
        ("escolaridade", escolaridade_map),
        ("nivel_ingles", idioma_map),
        ("nivel_espanhol", idioma_map)
    ]:
        if col in df2.columns:
            # Mapear valores e tratar não encontrados
            df2[col] = df2[col].map(lambda x: mapping.get(x.strip(), 0))
        else:
            df2[col] = 0

    return df2[["experiencia", "escolaridade", "nivel_ingles", "nivel_espanhol"]].fillna(0).astype(int)

# Navegação
menu = st.sidebar.radio("📂 Navegação", ["📌 Aplicar para Vagas", "🧠 Recrutamento Decision", "📊 Banco de Candidaturas"])

if menu == "📌 Aplicar para Vagas":
    st.title("📌 Plataforma de Vagas - Datathon")
    vagas = carregar_vagas()

    if vagas:
        escolha = st.selectbox("Selecione a vaga", options=[v["title"] for v in vagas])
        vaga = next(v for v in vagas if v["title"] == escolha)
        st.subheader(vaga["title"])
        st.write(f"**Empresa:** {vaga['company']}")
        st.write(f"**Localização:** {vaga['location']}")
        st.write(f"**Tipo de Contrato:** {vaga['contract_type']}")
        st.write(f"**Salário:** {vaga['salary']}")
        st.write(f"**Descrição:** {vaga['description']}")
        st.write(f"**Requisitos:** {vaga['requirements']}")

        # Inicializar lista de habilidades
        if 'habilidades' not in st.session_state:
            st.session_state.habilidades = []

        # Inicializar estados para campos do formulário
        for field in ['nome', 'email', 'linkedin', 'experiencia', 'escolaridade', 'nivel_ingles', 'nivel_espanhol']:
            if field not in st.session_state:
                st.session_state[field] = ''

        with st.form("form_candidatura"):  # REMOVIDO: clear_on_submit=True
            st.subheader("Formulário de Candidatura")
            nome = st.text_input("Nome Completo*", value=st.session_state.nome)
            email = st.text_input("Email*", value=st.session_state.email)
            linkedin = st.text_input("LinkedIn (opcional)", value=st.session_state.linkedin)
            experiencia = st.selectbox("Nível de Experiência*",
                                      list(experiencia_map.keys()),
                                      index=list(experiencia_map.keys()).index(st.session_state.experiencia)
                                      if st.session_state.experiencia in experiencia_map else 0)
            escolaridade = st.selectbox("Escolaridade*",
                                      list(escolaridade_map.keys()),
                                      index=list(escolaridade_map.keys()).index(st.session_state.escolaridade)
                                      if st.session_state.escolaridade in escolaridade_map else 0)
            nivel_ingles = st.selectbox("Inglês*",
                                      list(idioma_map.keys()),
                                      index=list(idioma_map.keys()).index(st.session_state.nivel_ingles)
                                      if st.session_state.nivel_ingles in idioma_map else 0)
            nivel_espanhol = st.selectbox("Espanhol*",
                                      list(idioma_map.keys()),
                                      index=list(idioma_map.keys()).index(st.session_state.nivel_espanhol)
                                      if st.session_state.nivel_espanhol in idioma_map else 0)

            # Seção de Habilidades
            st.subheader("Habilidades Técnicas")
            nova_habilidade = st.text_input(
                "Digite uma habilidade e clique em Adicionar",
                placeholder="Ex: Python, SQL, etc."
            )

            col_add, col_clear = st.columns(2)
            with col_add:
                adicionar_habilidade = st.form_submit_button("➕ Adicionar Habilidade")
            with col_clear:
                limpar_habilidades = st.form_submit_button("🧹 Limpar Todas")

            if adicionar_habilidade and nova_habilidade:
                st.session_state.habilidades.append(nova_habilidade.strip())
                st.rerun()

            if limpar_habilidades:
                st.session_state.habilidades = []
                st.rerun()

            if st.session_state.habilidades:
                st.write("**Habilidades adicionadas:**")
                for i, hab in enumerate(st.session_state.habilidades):
                    st.write(f"{i+1}. {hab}")

            enviar_cv = st.file_uploader("CV (PDF ou DOCX)")
            submitted = st.form_submit_button("Enviar Candidatura")

            if submitted:
                if not nome or not email:
                    st.error("Campos obrigatórios não preenchidos (Nome e Email)")
                else:
                    dados = {
                        "vaga": escolha,
                        "nome": nome,
                        "email": email,
                        "linkedin": linkedin,
                        "experiencia": experiencia,
                        "escolaridade": escolaridade,
                        "nivel_ingles": nivel_ingles,
                        "nivel_espanhol": nivel_espanhol,
                        "habilidades": ", ".join(st.session_state.habilidades) if st.session_state.habilidades else "Nenhuma",
                        "cv": enviar_cv.name if enviar_cv else "Nenhum"
                    }
                    if salvar_candidato_db(dados):
                        st.success("✅ Candidatura enviada com sucesso!")
                        # Resetar apenas habilidades
                        st.session_state.habilidades = []

                        # Manter outros campos
                        st.session_state.nome = nome
                        st.session_state.email = email
                        st.session_state.linkedin = linkedin
                        st.session_state.experiencia = experiencia
                        st.session_state.escolaridade = escolaridade
                        st.session_state.nivel_ingles = nivel_ingles
                        st.session_state.nivel_espanhol = nivel_espanhol
                    else:
                        st.error("❌ Erro ao salvar candidatura no banco de dados")

    else:
        st.info("Nenhuma vaga disponível. Verifique 'jobs_sample.json'.")

elif menu == "🧠 Recrutamento Decision":
    st.title("🧠 Recrutamento Decision - Análise Preditiva")
    uploaded = st.file_uploader("Upload do CSV de candidatos aplicados", type="csv")

    if uploaded:
        df = pd.read_csv(uploaded)
        st.success("Arquivo carregado!")
        st.dataframe(df.head())

        faltam = [c for c in ["experiencia","escolaridade","nivel_ingles","nivel_espanhol"] if c not in df.columns]
        if faltam:
            st.warning(f"Campos faltantes: {', '.join(faltam)}")
        st.subheader("Pré-processamento")
        X = preprocess(df)
        st.dataframe(X.head())

        if st.button("Analisar com Modelo"):
            try:
                mdl = joblib.load("modelo_vagas.pkl")
                df["score_sucesso"] = mdl.predict_proba(X)[:,1]
                st.subheader("🏆 Ranking de Candidatos")
                st.dataframe(df.sort_values("score_sucesso", ascending=False))

                st.subheader("📊 Distribuição de Scores")
                fig = px.histogram(df, x="score_sucesso", nbins=10)
                st.plotly_chart(fig)

                st.download_button(
                    "Exportar resultados",
                    data=df.to_csv(index=False).encode("utf-8"),
                    file_name="resultado_candidatos.csv",
                    mime="text/csv"
                )
            except Exception as e:
                st.error(f"Erro ao rodar modelo: {e}")

elif menu == "📊 Banco de Candidaturas":
    st.title("📊 Banco de Candidaturas")
    try:
        conn = sqlite3.connect('candidatos.db')
        df = pd.read_sql_query("SELECT * FROM candidaturas", conn)
        conn.close()

        if not df.empty:
            st.dataframe(df)

            st.download_button(
                "Exportar para CSV",
                data=df.to_csv(index=False).encode('utf-8'),
                file_name="candidaturas_completas.csv",
                mime="text/csv"
            )
        else:
            st.info("Nenhuma candidatura encontrada no banco de dados")
    except Exception as e:
        st.error(f"Erro ao acessar banco de dados: {e}")
""")

        # Iniciar o Streamlit em segundo plano
        print("⏳ Iniciando servidor Streamlit...")
        process = subprocess.Popen([
            "streamlit", "run", STREAMLIT_SCRIPT,
            "--server.port", "8501",
            "--server.headless", "true",
            "--server.enableCORS", "false",
            "--server.enableXsrfProtection", "false"
        ])

        # Esperar inicialização
        time.sleep(8)

        # Criar túnel Ngrok
        print("⏳ Criando túnel Ngrok...")
        public_url = ngrok.connect(addr="8501", proto="http", bind_tls=True)

        # Exibir link de acesso
        print("\n" + "="*50)
        print(f"🌟 APLICATIVO PUBLICADO COM SUCESSO!")
        print("="*50)
        print(f"🔗 ACESSE EM: {public_url.public_url}")
        print("="*50)
        print("Este link é válido enquanto esta sessão estiver ativa")
        print("Para desativar, interrompa a execução do notebook")

        # Manter o processo ativo
        try:
            while True:
                time.sleep(10)
                clear_output(wait=True)
                print(f"✅ Aplicativo ativo em: {public_url.public_url}")
                print("Pressione Ctrl+C para encerrar")
        except KeyboardInterrupt:
            print("\nEncerrando aplicativo...")
            process.terminate()
            ngrok.kill()
            os.remove(STREAMLIT_SCRIPT)  # Limpeza do arquivo temporário

    except Exception as e:
        print(f"Erro na configuração: {str(e)}")
        print("Certifique-se de que o token Ngrok está correto!")